#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
WORKSPACE=${WORKSPACE:-$SCRIPT_DIR/workspace}
MKPOD_BIN=${MKPOD_BIN:-$ROOT_DIR/bin/mkpod}
AWS_PROFILE=${AWS_PROFILE:-default}
AWS_REGION=${AWS_REGION:-eu-west-1}
INPUT_BUCKET=${INPUT_BUCKET:-mkpod-integration-test-assets}
OUTPUT_BUCKET=${OUTPUT_BUCKET:-mkpod-integration-test}
BASE_URL=${BASE_URL:-https://$OUTPUT_BUCKET.s3.$AWS_REGION.amazonaws.com}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: required command not found: $1" >&2
        exit 1
    fi
}

require_command ffmpeg

if [ ! -x "$MKPOD_BIN" ]; then
    echo "error: mkpod binary not found at $MKPOD_BIN" >&2
    exit 1
fi

mkdir -p "$(dirname "$WORKSPACE")"
if [ ! -f "$WORKSPACE/podspec.yaml" ]; then
    "$MKPOD_BIN" init "$WORKSPACE" >/dev/null
fi

mkdir -p "$WORKSPACE/artwork" "$WORKSPACE/masters"

ffmpeg -loglevel error -y -f lavfi -i color=c=0x2d6a4f:s=1600x1600:d=1 -frames:v 1 "$WORKSPACE/artwork/podcast-cover.jpg"
ffmpeg -loglevel error -y -f lavfi -i color=c=0x52796f:s=1600x1600:d=1 -frames:v 1 "$WORKSPACE/artwork/episode-1.jpg"
ffmpeg -loglevel error -y -f lavfi -i sine=frequency=440:sample_rate=48000 -t 2 "$WORKSPACE/masters/episode-1.wav"
ffmpeg -loglevel error -y -f lavfi -i sine=frequency=660:sample_rate=48000 -t 2 "$WORKSPACE/masters/episode-2.wav"

cat > "$WORKSPACE/podspec.yaml" <<SPEC
config:
    baseURL: $BASE_URL
    image: $BASE_URL/artwork/podcast-cover.jpg
    defaultPodImage: artwork/podcast-cover.jpg
    aws:
        profile: $AWS_PROFILE
        region: $AWS_REGION
        buckets:
            input: $INPUT_BUCKET
            output: $OUTPUT_BUCKET
    localStorageDir: $WORKSPACE
atom: podcast.rss
title: mkpod acceptance test
link: https://example.com/mkpod-acceptance
ttl: 60
language: en
copyright: Copyright mkpod acceptance test
webMaster: you@example.com
description: Acceptance-test workspace generated by e2e/bootstrap-workspace.sh.
subtitle: mkpod acceptance workspace
ownerName: Test Owner
ownerEmail: you@example.com
author: Test Owner
explicit: "no"
keywords: mkpod,acceptance,test
categories:
    - name: Technology
      subcategories: []
encoding:
    preferredFormat: m4a
    bitrate: 128
    lamepath: lame
    ffmpegpath: ffmpeg
    crf: 28
    abr: 128k
    coverfront: artwork/podcast-cover.jpg
    genre: Podcast
    language: eng
episodes:
    - uid: 1
      title: Acceptance Episode One
      pubDate: Mon, 01 Sep 2025 21:21:04 +0000
      link: https://example.com/mkpod-acceptance/episodes/1
      subtitle: Generated acceptance fixture one
      description: Generated by the mkpod AWS acceptance bootstrap script.
      image: artwork/episode-1.jpg
      input: masters/episode-1.wav
      chapters:
        - title: Intro
          start: "00:00:00.000"
    - uid: 2
      title: Acceptance Episode Two
      pubDate: Tue, 02 Sep 2025 21:21:04 +0000
      link: https://example.com/mkpod-acceptance/episodes/2
      subtitle: Generated acceptance fixture two
      description: Generated by the mkpod AWS acceptance bootstrap script.
      input: masters/episode-2.wav
SPEC

cp "$WORKSPACE/podspec.yaml" "$WORKSPACE/original-podspec.yaml"

echo "Bootstrapped workspace at $WORKSPACE"
